import { KeyboardKeyConfig } from "../types";

export const QWERTY_KEYBOARD: KeyboardKeyConfig[][] = [
  [
    { value: "`", size: "1u" },
    { value: "1", size: "1u" },
    { value: "2", size: "1u" },
    { value: "3", size: "1u" },
    { value: "4", size: "1u" },
    { value: "5", size: "1u" },
    { value: "6", size: "1u" },
    { value: "7", size: "1u" },
    { value: "8", size: "1u" },
    { value: "9", size: "1u" },
    { value: "0", size: "1u" },
    { value: "-", size: "1u" },
    { value: "=", size: "1u" },
    { label: "Delete", value: "delete", size: "1.5u" },
  ],
  [
    { label: "Tab", value: "tab", size: "1.5u" },
    { value: "q", size: "1u" },
    { value: "w", size: "1u" },
    { value: "e", size: "1u" },
    { value: "r", size: "1u" },
    { value: "t", size: "1u" },
    { value: "y", size: "1u" },
    { value: "u", size: "1u" },
    { value: "i", size: "1u" },
    { value: "o", size: "1u" },
    { value: "p", size: "1u" },
    { value: "[", size: "1u" },
    { value: "]", size: "1u" },
    { value: "\\", size: "1u" },
  ],
  [
    { label: "Caps", value: "caps", size: "1.75u" },
    { value: "a", size: "1u" },
    { value: "s", size: "1u" },
    { value: "d", size: "1u" },
    { value: "f", size: "1u" },
    { value: "g", size: "1u" },
    { value: "h", size: "1u" },
    { value: "j", size: "1u" },
    { value: "k", size: "1u" },
    { value: "l", size: "1u" },
    { value: ";", size: "1u" },
    { value: "'", size: "1u" },
    { label: "Enter", value: "enter", size: "1.75u" },
  ],
  [
    { label: "Shift", value: "left-shift", size: "2.5u" },
    { value: "z", size: "1u" },
    { value: "x", size: "1u" },
    { value: "c", size: "1u" },
    { value: "v", size: "1u" },
    { value: "b", size: "1u" },
    { value: "n", size: "1u" },
    { value: "m", size: "1u" },
    { value: ",", size: "1u" },
    { value: ".", size: "1u" },
    { value: "/", size: "1u" },
    { label: "Shift", value: "right-shift", size: "2.5u" },
  ],
];
