import { KeyMap } from "../types";

export const QWERTY_KEYBOARD: KeyMap = [
  [
    { value: "`", qwertyValue: "`", size: "1u" },
    { value: "1", qwertyValue: "1", size: "1u" },
    { value: "2", qwertyValue: "2", size: "1u" },
    { value: "3", qwertyValue: "3", size: "1u" },
    { value: "4", qwertyValue: "4", size: "1u" },
    { value: "5", qwertyValue: "5", size: "1u" },
    { value: "6", qwertyValue: "6", size: "1u" },
    { value: "7", qwertyValue: "7", size: "1u" },
    { value: "8", qwertyValue: "8", size: "1u" },
    { value: "9", qwertyValue: "9", size: "1u" },
    { value: "0", qwertyValue: "0", size: "1u" },
    { value: "-", qwertyValue: "-", size: "1u" },
    { value: "=", qwertyValue: "=", size: "1u" },
    { label: "Delete", value: "delete", qwertyValue: "delete", size: "1.5u" },
  ],
  [
    { label: "Tab", qwertyValue: "tab", value: "tab", size: "1.5u" },
    { value: "q", qwertyValue: "q", size: "1u" },
    { value: "w", qwertyValue: "w", size: "1u" },
    { value: "e", qwertyValue: "e", size: "1u" },
    { value: "r", qwertyValue: "r", size: "1u" },
    { value: "t", qwertyValue: "t", size: "1u" },
    { value: "y", qwertyValue: "y", size: "1u" },
    { value: "u", qwertyValue: "u", size: "1u" },
    { value: "i", qwertyValue: "i", size: "1u" },
    { value: "o", qwertyValue: "o", size: "1u" },
    { value: "p", qwertyValue: "p", size: "1u" },
    { value: "[", qwertyValue: "[", size: "1u" },
    { value: "]", qwertyValue: "]", size: "1u" },
    { value: "\\", qwertyValue: "\\", size: "1u" },
  ],
  [
    { label: "Caps", value: "caps", qwertyValue: "caps", size: "1.75u" },
    { value: "a", qwertyValue: "a", size: "1u" },
    { value: "s", qwertyValue: "s", size: "1u" },
    { value: "d", qwertyValue: "d", size: "1u" },
    { value: "f", qwertyValue: "f", size: "1u" },
    { value: "g", qwertyValue: "g", size: "1u" },
    { value: "h", qwertyValue: "h", size: "1u" },
    { value: "j", qwertyValue: "j", size: "1u" },
    { value: "k", qwertyValue: "k", size: "1u" },
    { value: "l", qwertyValue: "l", size: "1u" },
    { value: ";", qwertyValue: ";", size: "1u" },
    { value: "'", qwertyValue: "'", size: "1u" },
    { label: "Enter", value: "enter", qwertyValue: "enter", size: "1.75u" },
  ],
  [
    {
      label: "Shift",
      value: "left-shift",
      qwertyValue: "left-shift",
      size: "2.5u",
    },
    { value: "z", qwertyValue: "z", size: "1u" },
    { value: "x", qwertyValue: "x", size: "1u" },
    { value: "c", qwertyValue: "c", size: "1u" },
    { value: "v", qwertyValue: "v", size: "1u" },
    { value: "b", qwertyValue: "b", size: "1u" },
    { value: "n", qwertyValue: "n", size: "1u" },
    { value: "m", qwertyValue: "m", size: "1u" },
    { value: ",", qwertyValue: ",", size: "1u" },
    { value: ".", qwertyValue: ".", size: "1u" },
    { value: "/", qwertyValue: "/", size: "1u" },
    {
      label: "Shift",
      value: "right-shift",
      qwertyValue: "right-shift",
      size: "2.5u",
    },
  ],
];

export const DVORAK_KEYBOARD: KeyMap = [
  [
    { value: "`", qwertyValue: "`", size: "1u" },
    { value: "1", qwertyValue: "1", size: "1u" },
    { value: "2", qwertyValue: "2", size: "1u" },
    { value: "3", qwertyValue: "3", size: "1u" },
    { value: "4", qwertyValue: "4", size: "1u" },
    { value: "5", qwertyValue: "5", size: "1u" },
    { value: "6", qwertyValue: "6", size: "1u" },
    { value: "7", qwertyValue: "7", size: "1u" },
    { value: "8", qwertyValue: "8", size: "1u" },
    { value: "9", qwertyValue: "9", size: "1u" },
    { value: "0", qwertyValue: "0", size: "1u" },
    { value: "-", qwertyValue: "-", size: "1u" },
    { value: "=", qwertyValue: "=", size: "1u" },
    { label: "Delete", value: "delete", qwertyValue: "delete", size: "1.5u" },
  ],
  [
    { label: "Tab", qwertyValue: "tab", value: "tab", size: "1.5u" },
    { value: "'", qwertyValue: "q", size: "1u" },
    { value: ",", qwertyValue: "w", size: "1u" },
    { value: ".", qwertyValue: "e", size: "1u" },
    { value: "p", qwertyValue: "r", size: "1u" },
    { value: "y", qwertyValue: "t", size: "1u" },
    { value: "f", qwertyValue: "y", size: "1u" },
    { value: "g", qwertyValue: "u", size: "1u" },
    { value: "c", qwertyValue: "i", size: "1u" },
    { value: "r", qwertyValue: "o", size: "1u" },
    { value: "l", qwertyValue: "p", size: "1u" },
    { value: "/", qwertyValue: "[", size: "1u" },
    { value: "=", qwertyValue: "]", size: "1u" },
    { value: "\\", qwertyValue: "\\", size: "1u" },
  ],
  [
    { label: "Caps", value: "caps", qwertyValue: "caps", size: "1.75u" },
    { value: "a", qwertyValue: "a", size: "1u" },
    { value: "o", qwertyValue: "s", size: "1u" },
    { value: "e", qwertyValue: "d", size: "1u" },
    { value: "u", qwertyValue: "f", size: "1u" },
    { value: "i", qwertyValue: "g", size: "1u" },
    { value: "d", qwertyValue: "h", size: "1u" },
    { value: "h", qwertyValue: "j", size: "1u" },
    { value: "t", qwertyValue: "k", size: "1u" },
    { value: "n", qwertyValue: "l", size: "1u" },
    { value: "s", qwertyValue: ";", size: "1u" },
    { value: "-", qwertyValue: "'", size: "1u" },
    { label: "Enter", value: "enter", qwertyValue: "enter", size: "1.75u" },
  ],
  [
    {
      label: "Shift",
      value: "left-shift",
      qwertyValue: "left-shift",
      size: "2.5u",
    },
    { value: ";", qwertyValue: "z", size: "1u" },
    { value: "q", qwertyValue: "x", size: "1u" },
    { value: "j", qwertyValue: "c", size: "1u" },
    { value: "k", qwertyValue: "v", size: "1u" },
    { value: "x", qwertyValue: "b", size: "1u" },
    { value: "b", qwertyValue: "n", size: "1u" },
    { value: "m", qwertyValue: "m", size: "1u" },
    { value: "w", qwertyValue: ",", size: "1u" },
    { value: "v", qwertyValue: ".", size: "1u" },
    { value: "z", qwertyValue: "/", size: "1u" },
    {
      label: "Shift",
      value: "right-shift",
      qwertyValue: "right-shift",
      size: "2.5u",
    },
  ],
];
